import type { CareJob } from "@/domain/job";

export const DEMO_OWNER_ID = "00000000-0000-4000-8000-000000000001";

export const seedJob: CareJob = {
  id: "0190f8e4-93b1-7000-8000-000000000001",
  ownerId: DEMO_OWNER_ID,
  title: "Name the feeling",
  prompt:
    "Turn the central character into a calm, friendly red panda holding an emotion card. Preserve the quiet reading nook and leave generous space for facilitator copy.",
  audience: "children-6-9",
  mode: "img2img",
  inputUrl: "/assets/carecanvas-source.svg",
  simulateFirstQaFailure: false,
  status: "completed",
  sceneBrief: {
    refinedPrompt:
      "A warm editorial illustration of a friendly red panda in a quiet reading nook, holding a simple blank emotion card, soft natural shapes, calm teal and terracotta palette, generous negative space, no text or branding.",
    visualIntent: "A reassuring, age-appropriate activity card that invites conversation without diagnosing feelings.",
    preserve: ["quiet reading nook", "soft window light", "open space on the right"],
    avoid: ["medical claims", "readable text", "photorealistic child", "visual distress"],
    agent: "brief-agent",
  },
  safetyReview: {
    verdict: "pass",
    reasons: ["No diagnosis or treatment claim", "No identifying child imagery", "Language is age-appropriate"],
    childSafe: true,
    medicalClaimFree: true,
    agent: "safety-agent",
  },
  qaReview: {
    verdict: "pass",
    score: 94,
    checks: [
      { label: "Brief alignment", passed: true, note: "Character, setting and whitespace are preserved." },
      { label: "Child-safe visual", passed: true, note: "No distressing or identifying content detected." },
      { label: "Text integrity", passed: true, note: "No accidental generated lettering." },
    ],
    agent: "visual-qa-agent",
  },
  outputUrl: "/assets/carecanvas-result.svg",
  providerRequestId: "demo_seed_7wR39n0d",
  attempts: 1,
  trace: [
    {
      id: "seed-intake",
      name: "Input accepted",
      agent: "policy-gateway",
      state: "passed",
      startedAt: "2026-07-20T05:34:10.000Z",
      completedAt: "2026-07-20T05:34:10.018Z",
      durationMs: 18,
      attempt: 1,
      detail: "Schema valid · image URL normalized · budget reserved",
    },
    {
      id: "seed-brief",
      name: "Scene brief",
      agent: "brief-agent · demo adapter",
      state: "passed",
      startedAt: "2026-07-20T05:34:10.020Z",
      completedAt: "2026-07-20T05:34:10.642Z",
      durationMs: 622,
      attempt: 1,
      detail: "Intent structured into preserve / avoid constraints",
    },
    {
      id: "seed-safety",
      name: "Safety review",
      agent: "safety-agent · demo adapter",
      state: "passed",
      startedAt: "2026-07-20T05:34:10.645Z",
      completedAt: "2026-07-20T05:34:10.991Z",
      durationMs: 346,
      attempt: 1,
      detail: "Child-safe · claim-free · no personal data",
    },
    {
      id: "seed-human",
      name: "Human approval",
      agent: "content lead",
      state: "passed",
      startedAt: "2026-07-20T05:34:11.000Z",
      completedAt: "2026-07-20T05:35:02.000Z",
      durationMs: 51000,
      attempt: 1,
      detail: "Approved before provider spend",
    },
    {
      id: "seed-image",
      name: "Image edit",
      agent: "image-provider · bundled result",
      state: "passed",
      startedAt: "2026-07-20T05:35:02.010Z",
      completedAt: "2026-07-20T05:35:09.438Z",
      durationMs: 7428,
      attempt: 1,
      detail: "Bundled deterministic image completed",
      providerRequestId: "demo••••39n0d",
    },
    {
      id: "seed-qa",
      name: "Visual QA",
      agent: "visual-qa-agent · demo adapter",
      state: "passed",
      startedAt: "2026-07-20T05:35:09.441Z",
      completedAt: "2026-07-20T05:35:10.284Z",
      durationMs: 843,
      attempt: 1,
      detail: "Score 94/100 · output released",
    },
  ],
  createdAt: "2026-07-20T05:34:10.000Z",
  updatedAt: "2026-07-20T05:35:10.284Z",
};
